#!/bin/bash
#
# Testcase: Reload the vgem module
#
# ... we've broken this way too often :(
#

SOURCE_DIR="$( dirname "${BASH_SOURCE[0]}" )"
. $SOURCE_DIR/drm_getopt.sh

function unload() {
	/sbin/rmmod vgem
	# drm may be used by other devices (nouveau, radeon, udl, etc)
	/sbin/rmmod drm &> /dev/null

	if /sbin/lsmod | grep vgem &> /dev/null ; then
		echo WARNING: vgem.ko still loaded!
		return 1
	fi
}

unload &> /dev/null

/sbin/modprobe vgem $* || exit $IGT_EXIT_FAILURE
unload || exit $IGT_EXIT_FAILURE
