#!/bin/bash
#
# Testcase: Simulate gpu hang
#
# This check uses the stop_rings facility to exercise the gpu hang code.
# by reading /sys/kernel/debug/dri/0/i915_emon_status too quickly
#

SOURCE_DIR="$( dirname "${BASH_SOURCE[0]}" )"
. $SOURCE_DIR/drm_lib.sh

oldpath=`pwd`

cd $i915_dfs_path

if [ ! -f i915_ring_stop ] ; then
	echo "kernel doesn't support ring stopping"
	exit 77
fi

for estate_fname in $i915_dfs_path/i915_error_state $i915_sfs_path/error_state ; do
    echo checking ${estate_fname}

    if cat $estate_fname | grep -v "no error state collected" > /dev/null ; then
	echo "gpu hang detected"
	exit 1
    fi

    echo 0xf > i915_ring_stop
    echo "rings stopped"

    (cd $oldpath; $SOURCE_DIR/gem_exec_big) > /dev/null

    if cat $estate_fname | grep -v "no error state collected" > /dev/null ; then
	echo "gpu hang correctly detected"
    else
	echo "gpu hang not detected"
	exit 2
    fi

# clear error state
    echo > $estate_fname

    if cat $estate_fname | grep -v "no error state collected" > /dev/null ; then
	echo "gpu hang still present"
	exit 3
    fi
done

exit 0
